cloud-toolkit/cloud-toolkit-aws

.github/workflows/pull-request.yaml, provider/cmd/pulumi-resource-cloud-toolkit-aws/__tests__/example.ts, provider/cmd/pulumi-resource-cloud-toolkit-aws/babel.config.js, provider/cmd/pulumi-resource-cloud-toolkit-aws/jest.config.ts, provider/cmd/pulumi-resource-cloud-toolkit-aws/package-lock.json, provider/cmd/pulumi-resource-cloud-toolkit-aws/package.json
Run unit tests for provider on Pull Requests.
```release-note
NONE
```
=> Add unit tests for provider

provider/cmd/pulumi-resource-cloud-toolkit-aws/provider.ts, provider/cmd/pulumi-resource-cloud-toolkit-aws/serverless/queue.ts
/kind bug
- Fix Queue state in provider
- Register Queue outputs to let them accessible
```release-note
```
=> Fix queue state and outputs

schema.yaml, sdk/nodejs/types/enums/serverless/index.ts, sdk/python/cloud_toolkit_aws/serverless/_enums.py
/kind bug
Enums are not well defined in Shema and the generated SDK is not working correctly.
Fixes #21 
```release-note
Fix DeadLetterQueueTypes enum in Queue component
```
=> Fix Enums in schema

provider/cmd/pulumi-resource-cloud-toolkit-aws/landingzone/organization.ts
/kind bug
#49 
```release-note
Renamed Providers in LandingZone
```
=> Changing Provider names fro AWS Accounts in Organization

schema.yaml, sdk/nodejs/types/input.ts, sdk/nodejs/types/output.ts, sdk/python/cloud_toolkit_aws/databases/_inputs.py, sdk/python/cloud_toolkit_aws/email/_inputs.py, sdk/python/cloud_toolkit_aws/email/outputs.py, sdk/python/cloud_toolkit_aws/kubernetes/_inputs.py, sdk/python/cloud_toolkit_aws/landingzone/_inputs.py, sdk/python/cloud_toolkit_aws/landingzone/outputs.py, sdk/python/cloud_toolkit_aws/serverless/_inputs.py, sdk/python/cloud_toolkit_aws/storage/_inputs.py
/kind bug
`required` property is missing in schema Types.
#51 
```release-note
Fixed required properties in schema Types
```
=> Add required property in schema Types

provider/cmd/pulumi-resource-cloud-toolkit-aws/landingzone/accountIam.ts, provider/cmd/pulumi-resource-cloud-toolkit-aws/storage/bucket.ts
Uniform the component's source code.
```release-note
NONE
```
=> Set all components properties as readonly

provider/cmd/pulumi-resource-cloud-toolkit-aws/kubernetes/calico.ts, provider/cmd/pulumi-resource-cloud-toolkit-aws/kubernetes/calicoArgs.ts, provider/cmd/pulumi-resource-cloud-toolkit-aws/kubernetes/clusterAddons.ts, provider/cmd/pulumi-resource-cloud-toolkit-aws/kubernetes/dashboard.ts, provider/cmd/pulumi-resource-cloud-toolkit-aws/provider.ts, schema.yaml, sdk/nodejs/kubernetes/calico.ts, sdk/nodejs/kubernetes/clusterAddons.ts, sdk/nodejs/kubernetes/index.ts, sdk/nodejs/tsconfig.json, sdk/python/cloud_toolkit_aws/__init__.py, sdk/python/cloud_toolkit_aws/kubernetes/__init__.py, sdk/python/cloud_toolkit_aws/kubernetes/calico.py, sdk/python/cloud_toolkit_aws/kubernetes/cluster_addons.py
/kind feature
Adds the Calico addon to manage network policies.
https://github.com/cloud-toolkit/cloud-toolkit-aws/issues/35
```release-note
Adds Calico addon.
```
=> Calico addon

provider/cmd/pulumi-resource-cloud-toolkit-aws/kubernetes/cluster.ts, provider/cmd/pulumi-resource-cloud-toolkit-aws/kubernetes/clusterAddons.ts, provider/cmd/pulumi-resource-cloud-toolkit-aws/kubernetes/clusterAddonsArgs.ts, provider/cmd/pulumi-resource-cloud-toolkit-aws/kubernetes/clusterAutoscaler.ts, provider/cmd/pulumi-resource-cloud-toolkit-aws/kubernetes/clusterAutoscalerArgs.ts, provider/cmd/pulumi-resource-cloud-toolkit-aws/kubernetes/index.ts, provider/cmd/pulumi-resource-cloud-toolkit-aws/provider.ts, schema.yaml, sdk/nodejs/kubernetes/clusterAddons.ts
Migrate autoscaler component to SDK
Fixes #38 
None
```releasenote
Add ClusterAutoscaler component
```
=> Add ClusterAutoscaler component

Makefile
/kind bug
Python SDK version is not set when using makefile.
```release-note
NONE
```
=> Fix Python SDK version

provider/cmd/pulumi-resource-cloud-toolkit-aws/kubernetes/calico.ts, provider/cmd/pulumi-resource-cloud-toolkit-aws/kubernetes/cluster.ts, provider/cmd/pulumi-resource-cloud-toolkit-aws/kubernetes/clusterAddons.ts, provider/cmd/pulumi-resource-cloud-toolkit-aws/kubernetes/clusterAddonsArgs.ts, provider/cmd/pulumi-resource-cloud-toolkit-aws/kubernetes/clusterArgs.ts, provider/cmd/pulumi-resource-cloud-toolkit-aws/kubernetes/dashboard.ts, provider/cmd/pulumi-resource-cloud-toolkit-aws/kubernetes/externalDns.ts, provider/cmd/pulumi-resource-cloud-toolkit-aws/kubernetes/ingressNginx.ts, provider/cmd/pulumi-resource-cloud-toolkit-aws/kubernetes/ingressNginxArgs.ts, provider/cmd/pulumi-resource-cloud-toolkit-aws/provider.ts, schema.yaml, sdk/nodejs/kubernetes/cluster.ts, sdk/nodejs/kubernetes/clusterAddons.ts, sdk/nodejs/kubernetes/ingressNginx.ts, sdk/nodejs/types/input.ts, sdk/python/cloud_toolkit_aws/kubernetes/_inputs.py, sdk/python/cloud_toolkit_aws/kubernetes/cluster.py, sdk/python/cloud_toolkit_aws/kubernetes/cluster_addons.py, sdk/python/cloud_toolkit_aws/kubernetes/ingress_nginx.py, sdk/python/go.mod
/kind bug
/kind feature
Add an option in Kubernetes Cluster to create default IngressNginx instance.
Fixes #81 
```release-note
Add default IngressController in Kubernetes Cluster
Fixed calico race condition
Always redirect http to https in Kubernetes Cluster IngressController
```
=> Kubernetes default ingress

.github/workflows/release.yaml
=> Fix PythonSDK release with github actions

provider/cmd/pulumi-resource-cloud-toolkit-aws/kubernetes/index.ts, provider/cmd/pulumi-resource-cloud-toolkit-aws/kubernetes/irsa.ts, provider/cmd/pulumi-resource-cloud-toolkit-aws/provider.ts, sdk/nodejs/go.mod, sdk/python/README.md, sdk/python/go.mod
kind bug
IRSA was missing from the provider.ts. This made impossible its usage.
```release-note
Fixed IRSA component being missing from the provider specification. 
```
=> Added IRSA to provider.ts

provider/cmd/pulumi-resource-cloud-toolkit-aws/landingzone/accountIam.ts, provider/cmd/pulumi-resource-cloud-toolkit-aws/landingzone/auditLogging.ts, provider/cmd/pulumi-resource-cloud-toolkit-aws/landingzone/organization.ts
/kind bug
Fixing the unique type name for AccountIam, AuditLogging and Organization.
```release-note
Fixing the unique type name for AccountIam, AuditLogging and Organization.
```
=> Fixing ids for AccountIam, AuditLogging and Organization

Makefile
/kind bug
Fix the release process for the Python SDK.
```release-note
NONE
```
=> Install twine in the release process of Python SDK

provider/cmd/pulumi-resource-cloud-toolkit-aws/kubernetes/argocd.ts
Upgrades ArgoCD to 2.6.x
```release-note
ArgoCD upgraded to 2.6.x
```
=> Upped the chart version of ArgoCD

provider/cmd/pulumi-resource-cloud-toolkit-aws/package-lock.json, provider/cmd/pulumi-resource-cloud-toolkit-aws/package.json
Update `@pulumi/aws` version to support `eu-south-2` region.
Fix #127 
```release-note
Support `eu-south-2` region for Kubernetes Cluster component
```
=> Update @pulumi/aws to v5.35.0

provider/cmd/pulumi-resource-cloud-toolkit-aws/databases/auroraMysql.ts
/kind bug
AuroraMysql can't be created with custom VPC.
Fix #125
```release-note
Fix AuroraMysql when using custom VPC
```
=> Fix AuroraMysql when using custom VPC

provider/cmd/pulumi-resource-cloud-toolkit-aws/kubernetes/__tests__/fixtures/nodeGroup-minimal-configuration.ts, provider/cmd/pulumi-resource-cloud-toolkit-aws/kubernetes/__tests__/fixtures/nodeGroup-nodecount.ts, provider/cmd/pulumi-resource-cloud-toolkit-aws/kubernetes/clusterArgs.ts, schema.yaml, sdk/nodejs/kubernetes/cluster.ts, sdk/python/cloud_toolkit_aws/kubernetes/cluster.py
Upgrading Kubernetes version to 1.23
```release-note
Upgrading Kubernetes version to 1.23
```
=> Update k8s cluster to 1.23

sdk/python/cloud_toolkit_aws/databases/_enums.py, sdk/python/cloud_toolkit_aws/databases/aurora_mysql.py
Adding MySQL Aurora version fix to Python
```release-note
Fixed Aurora MySQL bug that  blocked the creation of new databases while using the Python SDK.
```
=> Added MySQL Aurora version fix to Python

provider/cmd/pulumi-resource-cloud-toolkit-aws/kubernetes/clusterArgs.ts, provider/cmd/pulumi-resource-cloud-toolkit-aws/kubernetes/nodeGroup.ts, provider/cmd/pulumi-resource-cloud-toolkit-aws/kubernetes/nodeGroupArgs.ts, schema.yaml, sdk/nodejs/kubernetes/nodeGroup.ts, sdk/nodejs/types/kubernetes/input.ts, sdk/python/cloud_toolkit_aws/kubernetes/_inputs.py, sdk/python/cloud_toolkit_aws/kubernetes/node_group.py
/kind feature
```release-note
Added block mapping for custom node disk size
```
=> Added block mapping for custom node disk size

provider/cmd/pulumi-resource-cloud-toolkit-aws/serverless/__tests__/staticweb.ts, provider/cmd/pulumi-resource-cloud-toolkit-aws/serverless/staticweb.ts, provider/cmd/pulumi-resource-cloud-toolkit-aws/serverless/staticwebArgs.ts, schema.yaml, sdk/nodejs/serverless/staticWeb.ts, sdk/nodejs/types/serverless/input.ts, sdk/python/cloud_toolkit_aws/serverless/_inputs.py, sdk/python/cloud_toolkit_aws/serverless/static_web.py
Adds the Hosted Zone ID of the Static Web DNS Records as optional parameter. This is required for some situations in which Hosted Zone resolution is not possible.
```release-note
Adds the Hosted Zone ID of the Static Web DNS Records as optional parameter.
```
=> Added hosted zone id as optional parameter for StaticWeb
